import type { Linter } from 'eslint';

export const baseRules: Linter.RulesRecord = {
	'array-callback-return': ['error', { checkForEach: true }],
	'constructor-super': ['error'],
	'for-direction': ['error'],
	'getter-return': ['error'],
	'no-async-promise-executor': ['error'],
	'no-class-assign': ['error'],
	'no-compare-neg-zero': ['error'],
	'no-cond-assign': ['error'],
	'no-const-assign': ['error'],
	'no-constant-binary-expression': ['error'],
	'no-constant-condition': ['error'],
	'no-constructor-return': ['error'],
	'no-control-regex': ['error'],
	'no-debugger': ['warn'],
	'no-dupe-args': ['error'],
	'no-dupe-class-members': ['error'],
	'no-dupe-else-if': ['error'],
	'no-dupe-keys': ['error'],
	'no-duplicate-case': ['error'],
	'no-duplicate-imports': ['error'],
	'no-empty-character-class': ['error'],
	'no-empty-pattern': ['error'],
	'no-ex-assign': ['error'],
	'no-fallthrough': ['error'],
	'no-func-assign': ['error'],
	'no-import-assign': ['error'],
	'no-invalid-regexp': ['error'],
	'no-irregular-whitespace': ['warn'],
	'no-loss-of-precision': ['error'],
	'no-misleading-character-class': ['warn'],
	'no-new-native-nonconstructor': ['error'],
	'no-obj-calls': ['error'],
	'no-promise-executor-return': ['error'],
	'no-prototype-builtins': ['error'],
	'no-self-assign': ['error'],
	'no-self-compare': ['error'],
	'no-setter-return': ['error'],
	'no-sparse-arrays': ['error'],
	'no-template-curly-in-string': ['warn'],
	'no-this-before-super': ['error'],
	'no-undef': ['warn'],
	'no-unexpected-multiline': ['error'],
	'no-unmodified-loop-condition': ['error'],
	'no-unreachable': ['error'],
	'no-unreachable-loop': ['error'],
	'no-unsafe-finally': ['error'],
	'no-unsafe-negation': ['error'],
	'no-unsafe-optional-chaining': ['error'],
	'no-unused-private-class-members': ['error'],
	'no-unused-vars': ['error'],
	'no-use-before-define': ['error'],
	'no-useless-assignment': ['error'],
	'no-useless-backreference': ['error'],
	'require-atomic-updates': ['error'],
	'use-isnan': ['error'],
	'valid-typeof': ['error'],
	'arrow-body-style': ['error', 'as-needed'],
	'block-scoped-var': ['error'],
	'class-methods-use-this': ['error'],
	'consistent-return': ['error', { treatUndefinedAsUnspecified: true }],
	'curly': ['error', 'multi'],
	'default-case-last': ['error'],
	'default-param-last': ['error'],
	'eqeqeq': ['error'],
	'func-names': ['error', 'never'],
	'func-style': ['error', 'expression'],
	'grouped-accessor-pairs': ['error'],
	'guard-for-in': ['error'],
	'max-classes-per-file': ['error', 1],
	'max-depth': ['error', 4],
	'max-nested-callbacks': ['warn', 3],
	'max-params': ['error', 4],
	'no-alert': ['error'],
	'no-array-constructor': ['error'],
	'no-bitwise': ['error'],
	'no-caller': ['error'],
	'no-console': ['warn'],
	'no-continue': ['error'],
	'no-delete-var': ['error'],
	'no-div-regex': ['error'],
	'no-else-return': ['error'],
	'no-empty': ['error'],
	'no-empty-function': ['error'],
	'no-empty-static-block': ['error'],
	'no-eval': ['error'],
	'no-extend-native': ['error'],
	'no-extra-bind': ['error'],
	'no-extra-boolean-cast': ['error'],
	'no-global-assign': ['error'],
	'no-implicit-coercion': ['warn'],
	'no-implied-eval': ['error'],
	'no-invalid-this': ['error'],
	'no-iterator': ['error'],
	'no-labels': ['error'],
	'no-lone-blocks': ['error'],
	'no-loop-func': ['error'],
	'no-multi-assign': ['error'],
	'no-multi-str': ['warn'],
	'no-nested-ternary': ['warn'],
	'no-new-func': ['error'],
	'no-new-wrappers': ['error'],
	'no-nonoctal-decimal-escape': ['error'],
	'no-object-constructor': ['error'],
	'no-octal': ['error'],
	'no-param-reassign': ['error'],
	'no-proto': ['error'],
	'no-redeclare': ['error'],
	'no-regex-spaces': ['error'],
	'no-return-assign': ['error'],
	'no-script-url': ['error'],
	'no-sequences': ['error'],
	'no-shadow': ['error'],
	'no-shadow-restricted-names': ['error'],
	'no-throw-literal': ['error'],
	'no-unneeded-ternary': ['error'],
	'no-unused-expressions': ['error'],
	'no-useless-call': ['error'],
	'no-useless-computed-key': ['error'],
	'no-useless-concat': ['error'],
	'no-useless-constructor': ['error'],
	'no-useless-escape': ['error'],
	'no-useless-rename': ['error'],
	'no-useless-return': ['error'],
	'no-var': ['error'],
	'no-void': ['error'],
	'no-with': ['error'],
	'object-shorthand': ['warn'],
	'operator-assignment': ['error', 'never'],
	'prefer-arrow-callback': ['error'],
	'prefer-const': ['error'],
	'prefer-exponentiation-operator': ['warn'],
	'prefer-object-has-own': ['error'],
	'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
	'prefer-rest-params': ['error'],
	'prefer-spread': ['error'],
	'prefer-template': ['error'],
	'radix': ['error'],
	'require-await': ['error'],
	'require-unicode-regexp': ['error'],
	'require-yield': ['error'],
	'yoda': ['error'],
	'import/export': ['error'],
	'import/no-deprecated': ['error'],
	'import/no-empty-named-blocks': ['error'],
	'import/no-extraneous-dependencies': [
		'error',
		{
			devDependencies: [
				'**/*.test.{mjs,cjs,js}',
				'**/*.stories.{mjs,cjs,js}',
				'storybook/**/*.{mjs,cjs,js}',
				'scripts/**/*.{mjs,cjs,js}',
				'mocks/**/*.{mjs,cjs,js}',
			],
		},
	],
	'import/no-named-as-default-member': ['error'],
	'import/no-mutable-exports': ['error'],
	'import/no-self-import': ['error'],
	'import/no-useless-path-segments': ['error'],
	'import/order': [
		'error',
		{
			'groups': [
				'type',
				'builtin',
				'external',
				'internal',
				'parent',
				'sibling',
				'index',
			],
			'alphabetize': {
				order: 'asc',
			},
			'newlines-between': 'never',
		},
	],
	'@stylistic/js/array-bracket-newline': ['error', 'consistent'],
	'@stylistic/js/array-bracket-spacing': ['error', 'never'],
	'@stylistic/js/array-element-newline': ['error', 'consistent'],
	'@stylistic/js/arrow-parens': ['error'],
	'@stylistic/js/arrow-spacing': ['error'],
	'@stylistic/js/block-spacing': ['error'],
	'@stylistic/js/brace-style': ['error', 'stroustrup'],
	'@stylistic/js/comma-dangle': ['error', 'always-multiline'],
	'@stylistic/js/comma-spacing': ['error'],
	'@stylistic/js/computed-property-spacing': ['error', 'never'],
	'@stylistic/js/dot-location': ['error', 'property'],
	'@stylistic/js/eol-last': ['error', 'always'],
	'@stylistic/js/function-call-spacing': ['error', 'never'],
	'@stylistic/js/function-paren-newline': ['error', 'consistent'],
	'@stylistic/js/generator-star-spacing': [
		'error',
		{
			before: false,
			after: true,
			anonymous: 'neither',
			method: { before: true, after: true },
		},
	],
	'@stylistic/js/implicit-arrow-linebreak': ['error', 'beside'],
	'@stylistic/js/indent': ['error', 'tab', { SwitchCase: 2 }],
	'@stylistic/js/key-spacing': ['error'],
	'@stylistic/js/lines-between-class-members': [
		'error',
		'always',
		{ exceptAfterSingleLine: true },
	],
	'@stylistic/js/max-len': [
		'error',
		{
			code: 130,
			tabWidth: 2,
			comments: 80,
			ignorePattern: '^import',
		},
	],
	'@stylistic/js/max-statements-per-line': ['error'],
	'@stylistic/js/new-parens': ['error'],
	'@stylistic/js/no-extra-parens': ['error'],
	'@stylistic/js/no-extra-semi': ['error'],
	'@stylistic/js/no-floating-decimal': ['error'],
	'@stylistic/js/no-mixed-operators': ['error'],
	'@stylistic/js/no-mixed-spaces-and-tabs': ['error'],
	'@stylistic/js/no-multi-spaces': ['error'],
	'@stylistic/js/no-multiple-empty-lines': ['error', { max: 1 }],
	'@stylistic/js/no-trailing-spaces': ['error'],
	'@stylistic/js/no-whitespace-before-property': ['error'],
	'@stylistic/js/object-curly-newline': ['error', { consistent: true }],
	'@stylistic/js/operator-linebreak': ['error', 'none'],
	'@stylistic/js/quote-props': ['error', 'consistent-as-needed'],
	'@stylistic/js/quotes': ['error', 'single'],
	'@stylistic/js/rest-spread-spacing': ['error', 'never'],
	'@stylistic/js/semi': ['error'],
	'@stylistic/js/semi-spacing': ['error'],
	'@stylistic/js/semi-style': ['error', 'last'],
	'@stylistic/js/space-before-blocks': ['error'],
	'@stylistic/js/space-before-function-paren': ['error'],
	'@stylistic/js/space-in-parens': ['error', 'never'],
	'@stylistic/js/space-infix-ops': ['error'],
	'@stylistic/js/space-unary-ops': ['error'],
	'@stylistic/js/switch-colon-spacing': ['error'],
	'@stylistic/js/template-curly-spacing': ['error'],
	'@stylistic/js/template-tag-spacing': ['error'],
};
